{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2019-10203",
        "ASSIGNER": "secalert@redhat.com",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "Red Hat",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "pdns",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "pdns versions 4.0.x before 4.0.9, 4.1.x before 4.1.11"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-681"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10203",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10203",
                "refsource": "CONFIRM"
            },
	    {
                "url": "https://doc.powerdns.com/authoritative/security-advisories/powerdns-advisory-2019-06.html",
                "name": "https://doc.powerdns.com/authoritative/security-advisories/powerdns-advisory-2019-06.html",
                "refsource": "CONFIRM"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "PowerDNS Authoritative daemon , pdns versions 4.0.x before 4.0.9, 4.1.x before 4.1.11, exiting when encountering a serial between 2^31 and 2^32-1 while trying to notify a slave leads to DoS."
            }
        ]
    },
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "4.3/CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                    "version": "3.0"
                }
            ]
        ]
    }
}
