{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2013-4346",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "The Server.verify_request function in SimpleGeo python-oauth2 does not check the nonce, which allows remote attackers to perform replay attacks via a signed URL."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "62386",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/62386"
            },
            {
                "name": "[oss-security] 20130912 Re: cve requests for python-oauth2",
                "refsource": "MLIST",
                "url": "http://www.openwall.com/lists/oss-security/2013/09/12/7"
            },
            {
                "name": "https://github.com/simplegeo/python-oauth2/issues/129",
                "refsource": "MISC",
                "url": "https://github.com/simplegeo/python-oauth2/issues/129"
            }
        ]
    }
}